/// Flutter icons SolanaWalletIcons
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  SolanaWalletIcons
///      fonts:
///       - asset: fonts/SolanaWalletIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';
import 'package:solana_wallet_provider/src/solana_wallet_constants.dart';

class SolanaWalletIcons {
  SolanaWalletIcons._();
  static const double size = 16.0;
  static const double strokeWidth = 1.25;
  static const _kFontFam = 'SolanaWalletIcons';
  static const String _kFontPkg = packageName;
  static const IconData copy = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData exclamationMark = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData tick = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData wallet = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}